@startuml\nskinparam backgroundColor #f7f7f7\nskinparam roundCorner 5\n\n!define PASTEL_COLOR_LIGHT #ffcccb\n!define PASTEL_COLOR_DARK #ff9999\n\nlayer "Group 1" {\n  box "Box 1" {\n    node "Node 1"\n  }\n  box "Box 2" {\n    node "Node 2"\n  }\n}\n\nlayer "Group 2" {\n  box "Box 3" {\n    node "Node 3"\n  }\n  box "Box 4" {\n    node "Node 4"\n  }\n}\n\nlayer "Group 3" {\n  box "Box 5" {\n    node "Node 5"\n  }\n  box "Box 6" {\n    node "Node 6"\n  }\n}\n@enduml